swagger: '2.0'
info:
  title: Travelway SAP integration
  description: Specification for integrating social mobile apps with Travelway SAP.
  version: 1.0.0
host: api.sap.travelway.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /customers:
    get:
      summary: Customers
      parameters:
        - name: updated_since
          in: query
          type: string
          format: dateTime
          required: false
          description: Instructs the server to only return items which have any changes since this specified datetime
      responses:
        '200':
          description: An array of customers.
          schema:
            type: array
            items:
              $ref: '#/definitions/Customer'
  /travellers:
    get:
      summary: All travellers
      description: |
        The Travellers endpoint returns information about the people who will be travelling. The response includes the email address, full name and mobile phone number of each traveller.
      parameters:
        - name: updated_since
          in: query
          type: string
          format: dateTime
          required: false
          description: Instructs the server to only return items which have any changes since this specified datetime
      responses:
        '200':
          description: An array of travellers.
          schema:
            type: array
            items:
              $ref: '#/definitions/Traveller'
  /trips:
    get:
      summary: All trips
      parameters:
        - name: updated_since
          in: query
          type: string
          format: dateTime
          required: false
          description: Instructs the server to only return items which have any changes since this specified datetime
      responses:
        '200':
          description: An array of all trips.
          schema:
            type: array
            items:
              $ref: '#/definitions/Trip'
definitions:
  Customer:
    type: object
    properties:
      id:
        type: string
        description: SAP identifier for this customer.
      name:
        type: string
        description: Customer name.
  Traveller:
    type: object
    properties:
      email:
        type: string
        description: Email address of the traveller.
      customer_id:
        type: string
        description: The id of the customer this traveller belongs to.
      full_name:
        type: string
        description: Full name of the traveller.
      mobile_phone:
        type: string
        description: Mobile phone number to the traveller.
  Trip:
    type: object
    properties:
      id:
        type: string
        description: SAP identifier for this trip.
      customer_id:
        type: string
        description: The id of the customer this trip belongs to.
      name:
        type: string
        description: Name of the trip.
      start_datetime:
        type: string
        description: RFC3339 full datetime for when the trip starts.
      end_datetime:
        type: string
        description: RFC3339 full datetime for when the trip ends.
      traveller_emails:
        type: array
        description: Email address of all travellers on this trip
        items:
          type: string